QPro/QPro/urls.py
from django.contrib import admin
from django.urls import path
from qapp import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('qapp/', include('qapp.urls')),
]

QPro/qapp/urls.py
from django.urls import path
from qapp import views

app_name = 'qapp'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

QPro/qapp/models.py
from django.db import models

# Create your models here.

QPro/qapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {
        'text':'hello world',
        'number':100,
    }
    return render(request, 'qapp/index.html', context=context_dict)

def other(request):
    return render(request, 'qapp/other.html')

def relative(request):
    return render(request, 'qapp/relative_url_templates.html')

QPro/templates/qapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class='navbar-link' href="{% url 'qapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      <!-- Anything outside of this tag will be inherited if you extend -->
      {% endblock %}

    </div>

  </body>
</html>

QPro/templates/qapp/index.html
<!DOCTYPE html>
{% extends 'qapp/base.html' %}
  {% block body_block %}
    <h1>Welcome to the index</h1>
    <h2>This is the index page</h2>
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ number|add:'99' }}</h1>
  {% endblock %}

QPro/templates/qapp/other.html
<!DOCTYPE html>
{% extends 'qapp/base.html' %}
  {% block body_block %}
    <h1>Welcome to 'Other'</h1>
    <h1>This is an example of template inheritence</h1>
  {% endblock %}

QPro/templates/qapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'qapp:other' %}">Click here to go to 'other'</a>
    <a href="{% url 'admin:index' %}">Click here to go to 'admin'</a>
    <a href="{% url 'index' %}">Link to 'index'</a>
  </body>
</html>